### ISSUE TITLE
Issue tracker

### ISSUE THREAD

**Issue by staffik** [near/near-one-project-tracking#101]
Task to track issues that come up during 2.4 release. 
Link tasks and Issues to this task for visibility.
When working on a fix, make sure to mark the PR with the appropriate `pick-` label. 
```[tasklist]
### Tasks
- [ ] https://github.com/near/nearcore/issues/12497
- [ ] https://github.com/near/nearcore/issues/12498
- [ ] https://github.com/near/nearcore/issues/12499
- [ ] https://github.com/near/nearcore/pull/12535
- [ ] https://github.com/near/nearcore/pull/12563
- [ ] https://github.com/near/nearcore/issues/12564
- [ ] https://github.com/near/nearcore/issues/12565
- [ ] https://github.com/near/nearcore/issues/12566
- [ ] https://github.com/near/nearcore/pull/12507
```
