### ISSUE TITLE
[ProjectTracking]: Stateless validation MVP

### ISSUE THREAD

**Issue by walnut-the-cat** [near/near-one-project-tracking#5]
# Goals

Horizontally scalable blockchain is what makes NEAR unique in the field. Currently, we have phase 1 of sharding in mainnet which is not a true form of sharding. With recent collaboration with various partners such as SWEAT and Kaiching, NEAR protocol has seen massive increase in daily txn volume and expect the number to grow beyond our current capacity in 2024. This naturally brings criticality of introducing the next phase of sharding in mainnet, so we can keep up with our growth.

As phase 1 of sharding requires block producers to track all shards due to underlying security concerns, the team explored potential ways to achieve phase 2 of sharding, where none of the validators has to track all shards.

Initial design of phase 2 relied on the security assumption that as long as there is one honest validator or fisherman tracking a shard, the shard is secure; by doing so, it naturally relied on protocol's ability to challenge (when an honest validator or fisherman detects a malicious behavior), rollback (when validators agree that the submitted challenge is valid), slashing (to punish the malicious validator), and rewarding (for chllenger). While it sounds straigtforward and simple on paper, the detailed implication and implementation of these features turned out to be extremely complicated.

As a result, the team sought alternative approach and concluded that stateless validation is the most realistic and promising one; stateless validation approach does not assume the existence of fishermen and assumes that a shard is secure if every single chunk in that shard is validated by a randomly sampled subset of all validators.

The fundamental idea is that validators do not need to have state locally to validate chunks. 
* Under stateless validation, responsibility of a chunk producer extends to package transactions and receipts and annotate them with state witnesses (we will call them with the new role name, chunk proposers).
* State witness of a chunk is defined to be the state alongside proof of inclusion that is needed to execute a chunk. State witness allows anyone to execute a chunk without having the state of a shard locally. 
* Then, validators will not store state locally and be randomly assigned to a shard at a given block height. Once a validator receives a chunk, along with its state witnesses, it verifies the state transition of the chunk, signs an approval, and sends it to the next block producer, similar to how it works today.

# Links to external documentations and discussions
* [Stateless validation index](https://docs.google.com/document/d/1gFv3GzPHR5CAX7_X2l5MpuMg7GIjW4Ne8e_3kZLnZQQ/edit?usp=sharing)
* [Stateless validation stage 0](https://docs.google.com/document/d/1C-w4FNeXl8ZMd_Z_YxOf30XA1JM6eMDp5Nf3N-zzNWU/edit?usp=sharing)
* [Stateless validation with pre-state root](https://docs.google.com/document/d/1k0NRMcLsDZp6C9pCRjNu5l7irDyRHsZ3VtKAKno_tFY/edit)
* [Stateless validation roadmap](https://docs.google.com/document/d/1TzMENFGYjwc2g5A3Yf4zilvBwuYJufsUQJwRjXGb9Xc/edit?usp=sharing)
* [Stateless validation dependency graph](https://miro.com/app/board/uXjVNXCSR5Y=/)
* [NEP-509](https://github.com/near/NEPs/pull/509/)
* [Zulip channel](https://near.zulipchat.com/#narrow/stream/407237-pagoda.2Fcore.2Fstateless-validation/topic/project.20progress)

# Estimated effort

The project started with three engineers, Alex, Anton, and Robin, and we plan to onboard more engineers. For now, the newly boarded engineers won't work on MVP, but building foundation for the next step.

We target all the necessary components to be landed by ~end of 2023~ early January, and connect the dots together and complete MVP in mid January for a demo-able MVP.

# Assumptions
* Decentralized State sync is enabled in Mainnet
* Initial round of shard split (4->5) is completed in Mainnet
* Merkle Patricia Trie is underlying data structure

# Tasks
## Major tasks (for MVP)
- [x] [In memory trie](https://github.com/near/nearcore/issues/9511): [REF](https://docs.google.com/document/d/1_X2z6CZbIsL68PiFvyrasjRdvKA_uucyIaDURziiH2U/edit?usp=sharing) @robin-near 
- [x] Validatior seat assignment @mooori 
- [x] Validator seat assignment integration with nearcore @robin-near 
- [x] State witness
  - [x] [generation](https://github.com/near/nearcore/issues/9628) (chunk proposer) @Longarithm 
  - [x] delivery (chunk proposer -> chunk validator) @robin-near 
  - [x] validation (chunk validator) @robin-near 
  - [x] [fill source_receipt_proofs](https://github.com/near/nearcore/issues/10443) @jancionear 
  - [x] [Transactions validation for Stateless Validation](https://github.com/near/nearcore/issues/10407) @staffik
  - [ ] delayed receipts handling
- [x] Chunk endorsement  
  - [x] generation (chunk validator) @robin-near
  - [x] collection (block producer) @shreyan-gupta
  - [x] block production - add chunk endorsements @shreyan-gupta 
  - [x] block processing - check chunk endorsements @shreyan-gupta 
- [x] Updated block validation and endorsement @robin-near 
- [x] [Test state witness generation and validation on a mainnet node](https://github.com/near/nearcore/issues/10440) @pugachAG 
- [x] metrics and dashboard @pugachAG 
- [x] Testing setup @robin-near 
  - [x] e.g. https://github.com/near/nearcore/pull/10524
- [x] Set up statelessnet feature, build the binary @Longarithm 
	- [ ] Consider adding dedicated CI
- [x] Figure out initial hardware requirements

**Comment by walnut-the-cat** [comment]
* Robin started working on state witness exchange and validation flow
* Alex is almost done with delayed chunk execution and will move on to state witness production
* Anton will start working on code refactoring for better dev env
* Shreyan will onboard with stateless validation and start tackling state witness size limit and distribution

**Comment by walnut-the-cat** [comment]
## Jan 16th Status update
* Jan([#10259](https://github.com/near/nearcore/issues/10259)) and Adam([#10414](https://github.com/near/nearcore/issues/10414)) started onboarding with Stateless validation
* Wac is also onboarding with Stateless validation to provide project management support
* [StatelessNet doc](https://docs.google.com/document/d/13QHL23KsFblZOIVhRHKaT5UhI9XCSclx6CCqoHsGD7s/edit?usp=sharing) has been written and reviewed by stakeholders
* All remaining tasks for Stateless validation MVP are WIP and e2e tests to prepare for StatelessNet will soon begin.

**Comment by Longarithm** [comment]
Feb 2nd update:

* Added support for chunk endorsements
* Conducted tests with 5/15 validator nodes; fixed discovered issues; reached relatively low percentage of missing chunks. Setting kickout threshold to 50% for now
* Metrics, more tests, replacing hacks with proper design
* Provided binary for StatelessNet

If there are no major issues with StatelessNet, I anticipate this to be closed as completed soon and we switch to https://github.com/near/near-one-project-tracking/issues/46.

**Comment by Longarithm** [comment]
Jan update from myself:
* Merging code for state proof production for state witness
* Adding signing&verifying state witness
* Reviewing PRs
* Helping with statelessnet launch and troubleshooting

**Comment by staffik** [comment]
2024 January update from myself:
* Onboarded to Stateless Validation.
* Stateless Transaction Validation.

**Comment by Longarithm** [comment]
Stateless was running for a week with some simple loadtesting. Closing as completed.
