### ISSUE TITLE
[ProjectTracking]: TestLoop Enhancements and Fixes

### ISSUE THREAD

**Issue by robin-near** [near/near-one-project-tracking#71]
# Goals

Make TestLoop generally usable for writing and maintaining integration tests.

# Issues

```[tasklist]
### Tasks
- [ ] https://github.com/near/nearcore/issues/11446
- [ ] https://github.com/near/nearcore/issues/11447
- [ ] https://github.com/near/nearcore/issues/11448
```

# Links to external documentations and discussions

N/A

# Estimated effort

Depends on individual issues

# Assumptions

N/A

# Pre-requisites

N/A

# Out of scope

N/A
