### ISSUE TITLE
[ProjectTracking]: Stateless validation MainNet launch prep

### ISSUE THREAD

**Issue by walnut-the-cat** [near/near-one-project-tracking#72]
- [ ] https://github.com/near/nearcore/issues/11656 @pugachAG @tayfunelmas 
- [x] https://github.com/near/near-one-project-tracking/issues/65 @staffik 
  - [x] https://github.com/near/nearcore/issues/11264 test
  - [x] in mem trie unloading test
  - [x] Confirm RPC node migration
  - [x] Confirm Archival node migration
  - [x] Gather hardware requirement during upgrade 
- [ ] https://github.com/near/near-one-project-tracking/issues/20 
  - [ ] Traffic generation program @telezhnaya , @jancionear, @staffik 
    - [x] ~~https://github.com/near/stakewars-iv/issues/8~~
    - [x] ~~https://github.com/near/stakewars-iv/issues/9~~
    - [x] https://github.com/near/stakewars-iv/issues/58
    - [x] https://github.com/near/stakewars-iv/issues/60
    - [x] https://github.com/near/stakewars-iv/issues/57
  - [ ] mainnet traffic + locust test
- [x] 100 node test @tayfunelmas 
  - [ ] mainnet traffic + locust test
- [x] [Stakeholder requirements prep](https://docs.google.com/document/u/1/d/1wYtJr79UscQjYPaAhfmuqUxQiKFDbWs04oQf2wpi6BU/edit)
- [x] https://github.com/near/NEPs/pull/509/
- [x] Validator AMA @telezhnaya 
  - [x] session 1 (July 2nd)
  - [x] session 2 (July 17th)
- [x] Cherry-pick https://github.com/near/nearcore/pull/11628 and https://github.com/near/nearcore/pull/11636 to statelessnet_master cc. @saketh-are 
- [x] Out-going size limit @jancionear 
- [x] TestNet release cc. @marcelo-gonzalez 
- [x] Automatically track single shard after protocol version upgrade
- [x] Investigate long block time with the first block of protocol v69
- [x] Incorrect tracking of current validator nodes [ref](https://near.zulipchat.com/#narrow/stream/407237-core.2Fstateless-validation/topic/bug.20in.20tracked.20shards/near/452618777)
