### ISSUE TITLE
[ProjectTracking]: Epoch Sync V4

### ISSUE THREAD

**Issue by robin-near** [near/near-one-project-tracking#73]
## Overview
* [doc](https://docs.google.com/document/d/14Itc9Hs7ewTRmcGANid9UCaYcJzaLzzM7FsvYYIFKDY/edit#heading=h.p2oiicluwd6o)
* [thread](https://near.zulipchat.com/#narrow/stream/295558-core/topic/Epoch.20sync.20questions)

## Issues (ongoing list):

Critical tasks:

```[tasklist]
### Tasks
- [ ] https://github.com/near/nearcore/issues/11932
- [ ] https://github.com/near/nearcore/issues/11933
- [ ] https://github.com/near/nearcore/issues/11935
- [ ] https://github.com/near/nearcore/issues/11937
- [ ] https://github.com/near/nearcore/issues/11955
- [ ] https://github.com/near/nearcore/issues/12091
- [ ] https://github.com/near/nearcore/issues/12142
- [ ] https://github.com/near/nearcore/issues/12227
- [ ] https://github.com/near/nearcore/issues/12256
- [ ] https://github.com/near/nearcore/issues/12255
- [ ] https://github.com/near/nearcore/issues/12258
- [ ] https://github.com/near/nearcore/issues/12259
- [ ] https://github.com/near/nearcore/issues/12309
- [ ] https://github.com/near/nearcore/issues/12310
- [ ] https://github.com/near/nearcore/issues/12311
- [ ] https://github.com/near/nearcore/issues/12260
- [ ] https://github.com/near/nearcore/issues/12347
```

Nice-to-have tasks:
```[tasklist]
### Tasks
- [ ] https://github.com/near/nearcore/issues/11976
- [ ] https://github.com/near/nearcore/issues/12348
- [ ] https://github.com/near/nearcore/issues/12349
- [ ] https://github.com/near/nearcore/issues/12351
- [ ] https://github.com/near/nearcore/issues/11930
- [ ] https://github.com/near/nearcore/issues/11936
- [ ] https://github.com/near/nearcore/issues/12228
- [ ] https://github.com/near/nearcore/issues/12229
- [ ] https://github.com/near/nearcore/issues/12564
- [ ] https://github.com/near/nearcore/issues/12565
- [ ] https://github.com/near/nearcore/issues/12566
```

Deprioritized (unimportant) tasks
```[tasklist]
### Tasks
- [ ] https://github.com/near/nearcore/issues/11931
- [ ] https://github.com/near/nearcore/issues/11938
- [ ] https://github.com/near/nearcore/issues/12129
```
