### ISSUE TITLE
[ProjectTracking]: OmniBridge NEP141-Connector 

### ISSUE THREAD

**Issue by karim-en** [near/near-one-project-tracking#78]
# Goals

OmniBridge is a new generation of bridges that brings assets issued on NEAR to all chains using Chain Signatures.
The bridge will be based [Chain Signatures](https://docs.near.org/build/chain-abstraction/chain-signatures/getting-started)

# Links to external documentations and discussions

1. https://hackmd.io/@vvNs0QmHR-uhQ4-90rbhlw/rykDgkyI0
2. https://hackmd.io/@karim1king/B1D_pJNjA
3. https://hackmd.io/@karim1king/S1sfSQOK0

# Estimated effort
1. Omni Prover: 1 day
2. Omni EVM prover: 4 days
3. Wormhole prover: 4 days
4. NEP141-locker: 2 weeks
5. Factory solidity contact: 1 week
6. Factory solidity contact with Wormhole: 1 week
7. Relayer: 4 weeks
8. Bridge SDK changes: 2 week
9. Implement tests: 2 weeks
10. Deploy & test contracts on testnet: 1 week
11. Frontend integration: 2 weeks
12. Test frontend: 1 week

```[tasklist]
### Tasks
- [ ] https://github.com/Near-One/omni-bridge/issues/4
- [ ] https://github.com/Near-One/omni-bridge/issues/3
- [ ] https://github.com/Near-One/omni-bridge/issues/6
- [ ] https://github.com/Near-One/omni-bridge/issues/5
- [ ] https://github.com/Near-One/omni-bridge/issues/15
- [ ] https://github.com/Near-One/omni-bridge/issues/2
- [ ] https://github.com/Near-One/omni-bridge/issues/11
- [ ] https://github.com/Near-One/omni-bridge/issues/12
- [ ] https://github.com/Near-One/omni-bridge/issues/53
- [ ] https://github.com/Near-One/omni-bridge/issues/50
- [ ] https://github.com/Near-One/omni-bridge/issues/49
```

**Comment by karim-en** [comment]
Progress update:
1. Omni Prover: 90%
2. Omni EVM prover: 90%
3. Wormhole prover: 30%
4. NEP141-locker: 75%
5. Factory solidity contact: 90%
6. Factory solidity contact with Wormhole: 0%
7. Relayer: 25%
8. Bridge SDK changes: 50%
9. Implement tests: 0%
10. Deploy & test contracts on testnet: 0%
11. Frontend integration: 2 weeks 0%
12. Test frontend: 0%
