### ISSUE TITLE
[ProjectTracking]: BTC light client

### ISSUE THREAD

**Issue by karim-en** [near/near-one-project-tracking#79]
# Goals

Light client consists of a smart contract on the NEAR network that stores block headers from the bitcoin network and an off-chain service which continuously synchronizes block headers from Bitcoin to that smart contract.
The core purpose of this light client is to validate If a particular transaction is included in the Blockchain network.

- [x] Audit fixes
- [x] Deploy and test on testnet
- [x] Deploy on mainnet
- [x] Implement tests

# Links to external documentations and discussions
N/A
# Estimated effort
8 Weeks

# Assumptions
N/A

# Pre-requisites
N/A

# Out of scope
N/A

```[tasklist]
### Tasks
- [ ] https://github.com/Near-One/btc-light-client-contract/issues/72
- [ ] https://github.com/Near-One/btc-light-client-contract/issues/68
- [ ] https://github.com/Near-One/btc-light-client-contract/issues/66
- [ ] https://github.com/Near-One/btc-light-client-contract/issues/58
- [ ] https://github.com/Near-One/btc-light-client-contract/issues/50
- [ ] https://github.com/Near-One/btc-light-client-contract/issues/70
```
